-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyOJ1BjNRzONTzLEA
C1reh3G4WRJAvcsEvf4SEeHoEDygCgYIKoZIzj0DAQehRANCAAQswuKTb5SqK/ix
IxgOqNuXvKg/KURt72KEJn1tHCzVdMD974wLGlbh8g6XQue1wcfisxiuefyn4h3m
/HMIh0gO
-----END PRIVATE KEY-----